const mockData = [
  {
    acceptedOn: '2022-10-21T17:22:58.426Z',
    billingAddress: {
      type: 'billing',
      addressee: 'Maxwell X Shick',
      line1: '86 Perkins Ct',
      line2: null,
      city: 'Haverhill',
      state: 'MA',
      country: 'US',
      postalCode: '01832',
    },
    comment: '',
    customerInfo: { fullName: 'Maxwell X Shick', email: 'kmshick@comcast.net' },
    customerPaid: { unit: 'USD', value: 0, string: '$ 0 ' },
    netAmount: { unit: 'USD', value: 0, string: '$ 0 ' },
    orderComment: '',
    orderId: 'b24-d16',
    paypalDetails: { orderId: null, payerId: null, captureId: null, refundId: null, refundReason: null, disputeId: null },
    purchasedItems: [
      {
        count: 3,
        rowTotal: { unit: 'USD', value: 0, string: '$ 0 ' },
        productId: '6313b14aad9f79845b0cd2ce',
        productName: 'TEST PRODUCT',
        productSlug: 'test-product',
        variantId: '6313b14b012d451aef4267df',
        variantName: 'TEST PRODUCT',
        variantSlug: 'test-product',
        variantSKU: null,
        variantImage: {
          fileId: '6313b12abfb65a4a7e708ee5',
          url: 'https://uploads-ssl.webflow.com/6093a81a3fecac7b23360f91/6313b12abfb65a4a7e708ee5_NOTS%20%26%20Crest%20(WhiteBG)_Black%20Font%20-%20White%20BG.png',
          alt: null,
        },
        variantPrice: { unit: 'USD', value: 0, string: '$ 0 ' },
        weight: 0,
        height: 0,
        width: 0,
        length: 0,
      },
    ],
    status: 'unfulfilled',
    stripeDetails: {
      customerId: null,
      chargeId: null,
      disputeId: null,
      paymentIntentId: null,
      paymentMethod: null,
      subscriptionId: null,
      refundId: null,
      refundReason: null,
    },
    totals: {
      subtotal: { unit: 'USD', value: 0, string: '$ 0 ' },
      extras: [{ type: 'discount', name: 'Discount (TESTINGCODE)', description: '', price: { unit: 'USD', value: 0, string: '$ 0 ' } }],
      total: { unit: 'USD', value: 0, string: '$ 0 ' },
    },
  },
  {
    acceptedOn: '2022-09-03T20:08:50.043Z',
    billingAddress: {
      type: 'billing',
      addressee: 'Maxwell X Shick',
      line1: '86',
      line2: null,
      city: 'Haverhill',
      state: 'MA',
      country: 'US',
      postalCode: '01832',
    },
    comment: '',
    customerInfo: { fullName: 'Maxwell X Shick', email: 'mshick@suffolk.edu' },
    customerPaid: { unit: 'USD', value: 15.87, string: '$ 15.87 ' },
    netAmount: { unit: 'USD', value: 15.87, string: '$ 15.87 ' },
    orderComment: '',
    orderId: 'aec-d69',
    paypalDetails: { orderId: null, payerId: null, captureId: null, refundId: null, refundReason: null, disputeId: null },
    purchasedItems: [
      {
        count: 1,
        rowTotal: { unit: 'USD', value: 15.87, string: '$ 15.87 ' },
        productId: '6313b14aad9f79845b0cd2ce',
        productName: 'TEST PRODUCT',
        productSlug: 'test-product',
        variantId: '6313b14b012d451aef4267df',
        variantName: 'TEST PRODUCT',
        variantSlug: 'test-product',
        variantSKU: null,
        variantImage: {
          fileId: '6313b12abfb65a4a7e708ee5',
          url: 'https://uploads-ssl.webflow.com/6093a81a3fecac7b23360f91/6313b12abfb65a4a7e708ee5_NOTS%20%26%20Crest%20(WhiteBG)_Black%20Font%20-%20White%20BG.png',
          alt: null,
        },
        variantPrice: { unit: 'USD', value: 15.87, string: '$ 15.87 ' },
        weight: 0,
        height: 0,
        width: 0,
        length: 0,
      },
    ],
    status: 'fulfilled',
    stripeDetails: {
      customerId: null,
      chargeId: null,
      disputeId: null,
      paymentIntentId: null,
      paymentMethod: null,
      subscriptionId: null,
      refundId: null,
      refundReason: null,
    },
    totals: {
      subtotal: { unit: 'USD', value: 15.87, string: '$ 15.87 ' },
      extras: [],
      total: { unit: 'USD', value: 15.87, string: '$ 15.87 ' },
    },
  },
  {
    acceptedOn: '2022-09-03T20:07:05.042Z',
    billingAddress: {
      type: 'billing',
      addressee: 'TESTIN SHIT',
      line1: '86 Perkins Court',
      line2: null,
      city: 'Haverhill',
      state: 'MA',
      country: 'US',
      postalCode: '01832',
    },
    comment: '',
    customerInfo: { fullName: 'TESTIN SHIT', email: 'mshick@suffolk.edu' },
    customerPaid: { unit: 'USD', value: 0, string: '$ 0 ' },
    netAmount: { unit: 'USD', value: 0, string: '$ 0 ' },
    orderComment: '',
    orderId: '55f-424',
    paypalDetails: { orderId: null, payerId: null, captureId: null, refundId: null, refundReason: null, disputeId: null },
    purchasedItems: [
      {
        count: 1,
        rowTotal: { unit: 'USD', value: 0, string: '$ 0 ' },
        productId: '6313b14aad9f79845b0cd2ce',
        productName: 'TEST PRODUCT',
        productSlug: 'test-product',
        variantId: '6313b14b012d451aef4267df',
        variantName: 'TEST PRODUCT',
        variantSlug: 'test-product',
        variantSKU: null,
        variantImage: {
          fileId: '6313b12abfb65a4a7e708ee5',
          url: 'https://uploads-ssl.webflow.com/6093a81a3fecac7b23360f91/6313b12abfb65a4a7e708ee5_NOTS%20%26%20Crest%20(WhiteBG)_Black%20Font%20-%20White%20BG.png',
          alt: null,
        },
        variantPrice: { unit: 'USD', value: 0, string: '$ 0 ' },
        weight: 0,
        height: 0,
        width: 0,
        length: 0,
      },
    ],
    status: 'unfulfilled',
    stripeDetails: {
      customerId: null,
      chargeId: null,
      disputeId: null,
      paymentIntentId: null,
      paymentMethod: null,
      subscriptionId: null,
      refundId: null,
      refundReason: null,
    },
    totals: { subtotal: { unit: 'USD', value: 0, string: '$ 0 ' }, extras: [], total: { unit: 'USD', value: 0, string: '$ 0 ' } },
  },
  {
    acceptedOn: '2022-09-03T20:03:10.877Z',
    billingAddress: {
      type: 'billing',
      addressee: 'TESTIN SHIT',
      line1: '86 Perkins Ct',
      line2: null,
      city: 'Haverhill',
      state: 'MA',
      country: 'US',
      postalCode: '01832',
    },
    comment: '',
    customerInfo: { fullName: 'TESTIN SHIT', email: 'hello@max.com' },
    customerPaid: { unit: 'USD', value: 0, string: '$ 0 ' },
    netAmount: { unit: 'USD', value: 0, string: '$ 0 ' },
    orderComment: '',
    orderId: '669-353',
    paypalDetails: { orderId: null, payerId: null, captureId: null, refundId: null, refundReason: null, disputeId: null },
    purchasedItems: [
      {
        count: 1,
        rowTotal: { unit: 'USD', value: 0, string: '$ 0 ' },
        productId: '6313b14aad9f79845b0cd2ce',
        productName: 'TEST PRODUCT',
        productSlug: 'test-product',
        variantId: '6313b14b012d451aef4267df',
        variantName: 'TEST PRODUCT',
        variantSlug: 'test-product',
        variantSKU: null,
        variantImage: {
          fileId: '6313b12abfb65a4a7e708ee5',
          url: 'https://uploads-ssl.webflow.com/6093a81a3fecac7b23360f91/6313b12abfb65a4a7e708ee5_NOTS%20%26%20Crest%20(WhiteBG)_Black%20Font%20-%20White%20BG.png',
          alt: null,
        },
        variantPrice: { unit: 'USD', value: 0, string: '$ 0 ' },
        weight: 0,
        height: 0,
        width: 0,
        length: 0,
      },
    ],
    status: 'unfulfilled',
    stripeDetails: {
      customerId: null,
      chargeId: null,
      disputeId: null,
      paymentIntentId: null,
      paymentMethod: null,
      subscriptionId: null,
      refundId: null,
      refundReason: null,
    },
    totals: { subtotal: { unit: 'USD', value: 0, string: '$ 0 ' }, extras: [], total: { unit: 'USD', value: 0, string: '$ 0 ' } },
  },
  {
    acceptedOn: '2022-09-03T20:02:06.137Z',
    billingAddress: {
      type: 'billing',
      addressee: 'You better Work',
      line1: 'Testng AGAIN',
      line2: null,
      city: 'Haverhill',
      state: 'MA',
      country: 'US',
      postalCode: '01832',
    },
    comment: '',
    customerInfo: { fullName: 'You better Work', email: 'nots.lifestyle@gmail.com' },
    customerPaid: { unit: 'USD', value: 0, string: '$ 0 ' },
    netAmount: { unit: 'USD', value: 0, string: '$ 0 ' },
    orderComment: '',
    orderId: '23f-615',
    paypalDetails: { orderId: null, payerId: null, captureId: null, refundId: null, refundReason: null, disputeId: null },
    purchasedItems: [
      {
        count: 1,
        rowTotal: { unit: 'USD', value: 0, string: '$ 0 ' },
        productId: '6313b14aad9f79845b0cd2ce',
        productName: 'TEST PRODUCT',
        productSlug: 'test-product',
        variantId: '6313b14b012d451aef4267df',
        variantName: 'TEST PRODUCT',
        variantSlug: 'test-product',
        variantSKU: null,
        variantImage: {
          fileId: '6313b12abfb65a4a7e708ee5',
          url: 'https://uploads-ssl.webflow.com/6093a81a3fecac7b23360f91/6313b12abfb65a4a7e708ee5_NOTS%20%26%20Crest%20(WhiteBG)_Black%20Font%20-%20White%20BG.png',
          alt: null,
        },
        variantPrice: { unit: 'USD', value: 0, string: '$ 0 ' },
        weight: 0,
        height: 0,
        width: 0,
        length: 0,
      },
    ],
    status: 'unfulfilled',
    stripeDetails: {
      customerId: null,
      chargeId: null,
      disputeId: null,
      paymentIntentId: null,
      paymentMethod: null,
      subscriptionId: null,
      refundId: null,
      refundReason: null,
    },
    totals: { subtotal: { unit: 'USD', value: 0, string: '$ 0 ' }, extras: [], total: { unit: 'USD', value: 0, string: '$ 0 ' } },
  },
  {
    acceptedOn: '2022-09-03T20:00:51.968Z',
    billingAddress: {
      type: 'billing',
      addressee: 'Maxwell X Shick',
      line1: 'Hello yes please work',
      line2: null,
      city: 'Haverhill',
      state: 'MA',
      country: 'US',
      postalCode: '01832',
    },
    comment: '',
    customerInfo: { fullName: 'Maxwell X Shick', email: 'maxwellshick@gmail.com' },
    customerPaid: { unit: 'USD', value: 0, string: '$ 0 ' },
    netAmount: { unit: 'USD', value: 0, string: '$ 0 ' },
    orderComment: '',
    orderId: 'dcc-f33',
    paypalDetails: { orderId: null, payerId: null, captureId: null, refundId: null, refundReason: null, disputeId: null },
    purchasedItems: [
      {
        count: 1,
        rowTotal: { unit: 'USD', value: 0, string: '$ 0 ' },
        productId: '6313b14aad9f79845b0cd2ce',
        productName: 'TEST PRODUCT',
        productSlug: 'test-product',
        variantId: '6313b14b012d451aef4267df',
        variantName: 'TEST PRODUCT',
        variantSlug: 'test-product',
        variantSKU: null,
        variantImage: {
          fileId: '6313b12abfb65a4a7e708ee5',
          url: 'https://uploads-ssl.webflow.com/6093a81a3fecac7b23360f91/6313b12abfb65a4a7e708ee5_NOTS%20%26%20Crest%20(WhiteBG)_Black%20Font%20-%20White%20BG.png',
          alt: null,
        },
        variantPrice: { unit: 'USD', value: 0, string: '$ 0 ' },
        weight: 0,
        height: 0,
        width: 0,
        length: 0,
      },
    ],
    status: 'unfulfilled',
    stripeDetails: {
      customerId: null,
      chargeId: null,
      disputeId: null,
      paymentIntentId: null,
      paymentMethod: null,
      subscriptionId: null,
      refundId: null,
      refundReason: null,
    },
    totals: { subtotal: { unit: 'USD', value: 0, string: '$ 0 ' }, extras: [], total: { unit: 'USD', value: 0, string: '$ 0 ' } },
  },
  {
    acceptedOn: '2022-09-03T19:57:55.537Z',
    billingAddress: {
      type: 'billing',
      addressee: 'Max',
      line1: '123 Hello World St',
      line2: null,
      city: 'Haverhill',
      state: 'MA',
      country: 'US',
      postalCode: '01832',
    },
    comment: '',
    customerInfo: { fullName: 'Max', email: 'maxwellshick@gmail.com' },
    customerPaid: { unit: 'USD', value: 9.23, string: '$ 9.23 ' },
    netAmount: { unit: 'USD', value: 9, string: '$ 9 ' },
    orderComment: '',
    orderId: '259-1bc',
    paypalDetails: { orderId: null, payerId: null, captureId: null, refundId: null, refundReason: null, disputeId: null },
    purchasedItems: [
      {
        count: 1,
        rowTotal: { unit: 'USD', value: 9.23, string: '$ 9.23 ' },
        productId: '6313b14aad9f79845b0cd2ce',
        productName: 'TEST PRODUCT',
        productSlug: 'test-product',
        variantId: '6313b14b012d451aef4267df',
        variantName: 'TEST PRODUCT',
        variantSlug: 'test-product',
        variantSKU: null,
        variantImage: {
          fileId: '6313b12abfb65a4a7e708ee5',
          url: 'https://uploads-ssl.webflow.com/6093a81a3fecac7b23360f91/6313b12abfb65a4a7e708ee5_NOTS%20%26%20Crest%20(WhiteBG)_Black%20Font%20-%20White%20BG.png',
          alt: null,
        },
        variantPrice: { unit: 'USD', value: 9.23, string: '$ 9.23 ' },
        weight: 0,
        height: 0,
        width: 0,
        length: 0,
      },
    ],
    status: 'unfulfilled',
    stripeDetails: {
      customerId: null,
      chargeId: null,
      disputeId: null,
      paymentIntentId: null,
      paymentMethod: null,
      subscriptionId: null,
      refundId: null,
      refundReason: null,
    },
    totals: {
      subtotal: { unit: 'USD', value: 9.23, string: '$ 9.23 ' },
      extras: [],
      total: { unit: 'USD', value: 9.23, string: '$ 9.23 ' },
    },
  },
];

let avgOrderVal = 0;
let avrOrderSize = 0;

const averagingFunction = (orderData) => {
  let totalPaid = 0;
  let totalOrderedItems = 0;

  for (const customerPurchase in orderData) {
    totalPaid += orderData[customerPurchase].customerPaid.value;
    orderData[customerPurchase].purchasedItems.forEach((item) => {
      return (totalOrderedItems += item.count);
    });
  }

  // Takes total of all orders and divides this by number of orders
  avgOrderVal = Math.round((totalPaid / orderData.length) * 100) / 100;
  // Takes every item ordered in all orders and divides them by the amount of orders
  avrOrderSize = Math.round((totalOrderedItems / orderData.length) * 100) / 100;

  // dispatch({ type: SET_AVG_ORDER_VAL, payload: avgOrderVal });
  // dispatch({ type: SET_AVG_ORDER_SIZE, payload: avrOrderSize });
  return totalOrderedItems;
};

describe('Tests: OrdersTable component', () => {
  averagingFunction(mockData);

  test('should return average of all orders size', () => {
    expect(avgOrderVal).toBe(3.59);
  });

  test('should return average of all orders value', () => {
    expect(avrOrderSize).toBe(1.29);
  });
});
